### ISSUE TITLE
Ported to Javascript

### ISSUE THREAD

**Issue by Fil** [yongyanghz/LAPJV-algorithm-c#2]
Hello, I've just ported your implementation to Javascript here https://github.com/Fil/lap-jv

I had to work around rounding errors that were leading to infinite loops — I don't know if they also appear in the CPP version.

Thank you!

**Comment by yongyanghz** [comment]
Hi Phil,
Sorry for late reply. But Have you solved your problem or find errors in my
code? If not I will  check the code again. Please let me know if your code
work or not. Thanks.

Yong Yang

**Comment by Fil** [comment]
Please check the value of `epsilon` in my version. Without it my tests were quite often going into infinite loops, because of rounding errors. With epsilon I don't have this problem anymore. I'm sorry I don't have a reproductible example at hand, I think it was when there were around 5000 positions to optimize.

**Comment by Fil** [comment]
Here is a reproducible test:
https://gist.github.com/Fil/377f9aa3f8f07c428d54eec3564f0eba

run it with node.js; if you change `epsilon` to 0 on line 82, you quite often get into an infinite loop because of rounding errors on the tests

**Comment by yongyanghz** [comment]
Hi Fil,
I found an bug in my code, in gnrl.h file, the row and col type should be int, not double,I have fixed it and now the cpp version can work. Since I'm not familiar with java script, I haven't find error in your js version.

**Comment by Fil** [comment]
To be clear: the JS version works well.

However it is not strictly a port of your C code: the difference is this `epsilon` that I added, otherwise it would sometimes go into an infinite loop.

My question is if the C version also has this problem when two distances are very close and the comparison fails because of rounding.

**Comment by yongyanghz** [comment]
Hi Phil,
I see your add epsilon as tolerance in js version. Some cased can cause Jonker's code to loop forever. According to Dr. Volgenant, "The failure is a consequence of a tolerance not suited for the data ... You have to reduce the value of the tolerance such that it is smaller than the smallest difference between any pair of cost elements in the cost matrix."
You can also see Nota Bena part in [this link](https://github.com/hrldcpr/pyLAPJV#nota-bene).

Yong Yang

**Comment by Fil** [comment]
Thank you I will mention my solution there too. Maybe a good solution will come out of this!
