### ISSUE TITLE
type issues that can lead to possible overflows

### ISSUE THREAD

**Issue by Dharmesh946** [yongyanghz/LAPJV-algorithm-c#7]
During algorithm execution, according to `cost` nature and range of values in assigncost, some variables can overflow, noticeably `d`, `v`. 

For instance, if `cost` is `std::uintxx_t` I observed that some negative values can occurred when reducing cost. On the tests I did, it happened to work anyway due to modulo arithmetic with integers but I'm not sure that larger overflows can not occur, leading failure in the algorithm.

Even if `cost` is `double` or the largest possible integer, some computations may overflow (typically the final total cost).

Besides `BIG` is not large enough. Why not set it to `std::numeric_limits<cost>::max()`?

I don't understand the algorithm (neither from the code, nor the original paper) and I'm enable yet to determine if it has properties that limits the range of possible internal values according to input costs range.

Could it be possible to do this analysis and improve the computation safety (wrt overflows)?

Btw, `free` could be holding booleans? Am I right? And it should be rename as it collisions with a langage keyword.

**Comment by yongyanghz** [comment]
Hi Dharmesh,
Thanks for your valuable feedback and suggestions.
For the following issues:
1.  `double` data type Overflow issue: 
    Yes, it does exist when accumulate the path cost, `double` lost its precision: check this [stackoverflow link](https://stackoverflow.com/questions/41492080/double-overflow)
2.  Besides BIG is not large enough. Why not set it to std::numeric_limits<cost>::max()?
    Yes, set it to std::numeric_limits<cost>::max() is rational.
3.  `free ` is not a good name for variable, should be renamed.

I will modify and test the code according to the above suggestions, and update the code.

Best regards,
Yong Yang

**Comment by yongyanghz** [comment]
Updated code.

**Comment by yongyanghz** [comment]
Integer type for cost in not suggested due to the overflow issue,  always use double for cost.
